name: test-timeouts
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      test-timeouts
  workflow_dispatch:
jobs:
  smoketest:
    name: Hit smoketests against Charts in Dev Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install K3D
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Run the Charts in Dev Mode
        run: |
          pushd dev
          source ./.envrc
          make all
